# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-11-04 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djpaypal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingplan',
            name='key',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
